FROM python:3.4-onbuild
RUN apt-get update
RUN apt-get install libgeos-3.4.2 libgeos-c1 libgeos-dev
RUN apt-get install libpng-dev
RUN pip3 install https://github.com/matplotlib/basemap/archive/v1.1.0.tar.gz